from ai_helper import call_ai

class InterviewerAgent:
    
    def generate_question(self, state):
        if state.topic is None:
            return "What is the process you would like to describe?"

        conversation_text = state.get_conversation_text()
            
        prompt = f"""
        Attention: You're being used for an API call.
        You are the Interview Agent in a multi-agent interview system.

        Your job is to ask the user exactly ONE clear, concise question at a time
        to collect all the necessary details about the process titled: "{state.topic}".
        
        Current conversation you and the user had so far (Note that the questions in this conversation are also generated by you):
        {conversation_text}

        Guidelines:
        - Do NOT answer questions yourself. Only ask.
        - Do NOT ask general questions or questions involving multiple aspects of the topic.
        - Do NOT ask multiple things at once. Split complex asks into separate turns.
        - Avoid repeating questions already asked in this conversation.
        - Avoid asking about aspects that have been already covered in the conversation.
        - Avoid generic filler (like "tell me more"). Always target missing details.
        - Be polite but direct. Keep questions under 25 words.
        - Ask about these aspects (ONLY if the topic contains them) until they are covered (Note: Some aspects might not be applicable to every process, but you must cover the key ones.):
            - The purpose of the process.
            - Inputs/Ingrediants/Materials needed for the process.
            - Tools or resources required.
            - Step-by-step instructions. (Note: Don't ask about a single step of the process.)
            - Actors (who performs the process).
            - Exceptions and how to handle them.
            - Preconditions (what must be true before starting).
            - Postconditions (what will be true after).
            - Success criteria.
            - Examples if available.
        - If an aspect is covered in previous questions, do NOT ask about it.
        - Prefer open-ended questions ("What…", "How…") unless a yes/no check is best.
        - If the user’s last answer was vague, ask a clarifying question.

        Now generate the next interviewer question. Make sure that you ONLY write the question.
        The user must feel they're talking to an interviewer, not an AI.
        """
        
        question = call_ai(prompt)
        if question is None:
            return "Can you tell me more about the process?"
        
        question = question.strip()
        if question.startswith('"') and question.endswith('"'):
            question = question[1:-1]
        
        return question